Mydjango/urls.py
from django.urls import path
from django.conf.urls import include, url
import xadmin
from django.views.generic import TemplateView
from users.views import LoginView, RegisterView, ActiveView, ForGetPwdView, ResetView, ModifyPwdView, UserLoginView, LogoutView, IndexView
from organization.views import OrgView
# 同于处理django的静态文件
from django.views.static import serve
from Mydjango.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^login/', LoginView.as_view(), name='login'),
    # url('^login/', UserLoginView.as_view(), name='login'),
    url('^register/', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveView.as_view(), name='active'),
    url('^forget/', ForGetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name='reset_pass'),
    url('^modify/', ModifyPwdView.as_view(), name='modify'),
    # 课程机构url 配置
    url(r'^org/', include(('organization.urls', 'organization'), namespace='org')),

    # 课程机构url 配置
    url(r'^course/', include(('courses.urls', 'courses'), namespace='courses')),

    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    # 课程机构url配置

    # 个人中心url配置
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),

    # 退出登录
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

apps/courses/urls.py
#coding=utf-8
__author__ = 'kai.yang'
__date__ = '2019/10/12 22:24'
from django.urls import path
from django.conf.urls import include, url
import xadmin
from django.views.generic import TemplateView

# 同于处理django的静态文件
from django.views.static import serve
from Mydjango.settings import MEDIA_ROOT
from .views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentView, CourseAddCommentView, VideoPlayView

urlpatterns = [
    # 课程列表页
    url('^list/', CourseListView.as_view(), name='course_list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    url(r'^add_comment/', CourseAddCommentView.as_view(), name='course_add_comment'),
    url(r'^video_play/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
#coding=utf-8
__author__ = 'kai.yang'
__date__ = '2019/9/8 22:24'
from django.urls import path
from django.conf.urls import include, url
import xadmin
from django.views.generic import TemplateView
from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseeView, OrgDescView, OrgTeacherView, AddFavView, TeacherListView, TeacherDetailView
# 同于处理django的静态文件
from django.views.static import serve
from Mydjango.settings import MEDIA_ROOT

urlpatterns = [
    url('^list/', OrgView.as_view(), name='org_list'),
    url('^add_ask/', AddUserAskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>.*)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>.*)/$', OrgCourseeView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>.*)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^teacher/(?P<org_id>.*)/$', OrgTeacherView.as_view(), name='org_teacher'),
    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
    # 讲师列表
    url(r'^teachers/list/$', TeacherListView.as_view(), name='teacher_list'),
    # 讲师详情
    url(r'^teachers/detail/(?P<teacher_id>.*)/$', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
#coding=utf-8
__author__ = 'kai.yang'
__date__ = '2019/11/2 22:24'
from django.urls import path
from django.conf.urls import include, url
import xadmin
from django.views.generic import TemplateView
from .views import UsersInfoView, UserUploadView, UpdateModifyPwdView, SendEmailCodeView, UpdateEmailView, MyCourseView
from .views import MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView, UserLoginView
# 同于处理django的静态文件
from django.views.static import serve
from Mydjango.settings import MEDIA_ROOT

urlpatterns = [
    url('^info/$', UsersInfoView.as_view(), name='users_center'),
    url('^image/upload/$', UserUploadView.as_view(), name='users_upload'),
    url('^update/pwd/$', UpdateModifyPwdView.as_view(), name='user_update_pwd'),
    # 发送邮箱验证码
    url('^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),

    # 修改邮箱
    url('^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    # 我的课程
    url('^my_course/$', MyCourseView.as_view(), name='users_course'),

    # 我收藏的课程机构
    url('^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),

    # 我收藏的授课教师
    url('^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # 我收藏的课程
    url('^myfav/course/$', MyFavCourseView.as_view(), name='myfav_course'),

    # 我的消息
    url('^mymessage/$', MyMessageView.as_view(), name='mymessage'),
]

apps/courses/models.py
#coding=utf-8

from django.db import models
from datetime import datetime
from organization.models import CourseOrg, Teacher

# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程机构', null=True, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='课程名称', max_length=50, default='1')
    desc = models.CharField(verbose_name='课程描述', max_length=200, default='1')
    detail = models.TextField(verbose_name='课程详情', max_length=200, default='1')
    is_banner = models.BooleanField(default=False, verbose_name='是否为轮播图')
    degree = models.CharField(choices=(('cj', u'初级'), ('zj', u'中级'), ('gj', u'高级')), verbose_name='课程难度', max_length=10, default='中级')
    learn_times = models.IntegerField(default=0, verbose_name='学习时长')
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name=u'logo')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    category = models.IntegerField(default="后端开发", verbose_name='课程类别')
    tags = models.CharField(default="", verbose_name='课程标记', max_length=20)
    teacher = models.ForeignKey(Teacher, verbose_name='讲课老师', null=True, on_delete=models.CASCADE, default='1')
    instructions = models.CharField(max_length=200, default='', verbose_name='课程须知')
    learning = models.CharField(max_length=200, default='', verbose_name='能学到什么')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def get_chapter_num(self):
        chapter_num = self.lesson_set.all().count()
        return chapter_num

    def get_learn_users(self):
        return self.usercourse_set.all()

    def get_course_resource(self):
        return self.courseresource_set.all()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    # 外键关联
    courses = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='章节名', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def get_videos(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    # 外键关联
    courses = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'视频名',  default='')
    url = models.CharField(max_length=200, verbose_name=u'播放链接', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    # 外键关联
    course = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='名称', default='')
    download = models.FileField(upload_to='courses/resource/%Y%m', verbose_name='下载链接')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/course-comment.html
{% extends 'base.html' %}
{#load 需要再extends之后添加#}
{% load staticfiles %}
{% block title %} 课程列表 - 慕学在线网 {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}">
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
                <li><a href="{% url 'courses:course_detail' curr_course.id %}">课程详情</a>></li>
                <li>{{ curr_course.name }}</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ curr_course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ curr_course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ curr_course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ curr_course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'courses:course_info' curr_course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'courses:course_comment' curr_course.id  %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" maxlength="100" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for comment in all_comments %}
                               <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.user }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in curr_course.get_course_resource %}
                                <li>
                                    <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                    <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ curr_course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ curr_course.teacher }}</a>
        </span>
                            <span class="job">{{ curr_course.course_org }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ curr_course.instructions }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ curr_course.learning }}</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        {% for resource_course in resource_courses %}
                                            <li class="curr">
                                                <a href="{% url 'courses:course_detail' resource_course.id  %}" target="_blank">
                                                    <img src="{{ MEDIA_URL }}{{ resource_course.image }}" alt="Java入门第一季">
                                                    <span class="name autowrap">{{ resource_course.name }}</span>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
    <script src="../js/selectUi.js" type='text/javascript'></script>
    <script src="../js/deco-common.js" type='text/javascript'></script>
    <script type="text/javascript" src="../js/plugins/laydate/laydate.js"></script>
    <script src="../js/plugins/layer/layer.js"></script>
    <script src="../js/plugins/queryCity/js/public.js" type="text/javascript"></script>
    <script src="../js/unslider.js" type="text/javascript"></script>
    <script src="../js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
    <script src="../js/deco-common.js"  type="text/javascript"></script>
    <script type="text/javascript">
        //添加评论
        $('#js-pl-submit').on('click', function(){
            var comments = $("#js-pl-textarea").val()
            if(comments == ""){
                alert("评论不能为空")
                return
            }
            $.ajax({
                cache: false,
                type: "POST",
                url:"/course/add_comment/",
                data:{'course_id':{{ curr_course.id }}, 'comments':comments},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    if(data.status == 'fail'){
                        if(data.msg == '用户未登录'){
                            window.location.href="login.html";
                        }else{
                            alert(data.msg)
                        }

                    }else if(data.status == 'success'){
                        window.location.reload();//刷新当前页面.
                    }
                },
            });
        });
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{#load 需要再extends之后添加#}
{% load staticfiles %}
{% block title %} 课程机构列表 - 慕学在线网 {% endblock %}
{% block custom_bread %}
{% endblock %}
{% block content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banner %}
                                <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'courses:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for courses_banner in all_course_banner %}
                                        <li>
                                        <a href="{% url 'courses:course_detail' courses_banner.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ courses_banner.image }}" />
                                        </a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for courses in all_courses %}
                                <div class="module1_{{ forloop.counter|add:'2' }} box">
                                    <a href="{% url 'courses:course_detail' courses.id %}">
                                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ courses.image }}"/>
                                    </a>
                                    <div class="des">
                                        <a href="{% url 'courses:course_detail' courses.id %}">
                                            <h2 title="django入门">{{ courses.name }}</h2>
                                        </a>
                                        <span class="fl">难度：<i class="key">{{ courses.get_degree_display }}</i></span>
                                        <span class="fr">学习人数：{{ courses.students }}</span>
                                    </div>
                                    <div class="bottom">
                                        <span class="fl" title="慕课网">{{ courses.course_org }}</span>
                                        <span class="star fr">{{ courses.fav_nums }}</span>
                                    </div>
                                </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in all_org %}
                                <li class="{% if forloop.counter == 5 %}five{% endif %}">
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>全国知名</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="慕课网">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}
13533630193@163.com

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程- 慕学在线网{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="/user/home/">个人信息</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li {% if current_tab == 'org' %}class="active"{% endif %}><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li {% if current_tab == 'teacher' %}class="active"{% endif %}><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li {% if current_tab == 'course' %}class="active"{% endif %}><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                            <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程- 慕学在线网{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="/user/home/">个人信息</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li {% if current_tab == 'org' %}class="active"{% endif %}><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li {% if current_tab == 'teacher' %}class="active"{% endif %}><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li {% if current_tab == 'course' %}class="active"{% endif %}><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                        <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="1"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter-base.html' %}
{% block title %}我的课程- 慕学在线网{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="/user/home/">我的课程</a>></li>
            <li>我的课程</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in request.user.get_user_course %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' user_course.course.id %}"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.course_org }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ user_course.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</div>
{% endblock %}